# Generated by Django 4.2.3 on 2023-08-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(default='color', max_length=200),
            preserve_default=False,
        ),
    ]
