# Generated by Django 4.2.3 on 2023-09-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='user',
        ),
        migrations.AlterField(
            model_name='pago',
            name='numeroFactura',
            field=models.TextField(null=True),
        ),
    ]
